name: Node.js CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检查
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: 安装 pnpm
        with:
          version: 9
          run_install: false
      - name: 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: 下载依赖
        run: pnpm install
      - name: 构建文档
        run: pnpm run docs:build --if-present
